### ISSUE TITLE
A question: how to make it working on Linux terminal?

### ISSUE THREAD

**Issue by kgfly** [fabiospampinato/vscode-debug-launcher#4]
On Ubuntu 18 LTS,

open 'vscod;5C;5^C//fabiospampinato.vscode-debug-launcher/launch?args={"type":"node","name":"Foo","request":"launch","program":"/path/to/foo.js"}'

prompts:

Couldn't get a file descriptor referring to the console

**Comment by fabiospampinato** [comment]
First of all does `/path/to/foo.js` exist? 

And this: "vscod;5C;5^C//" doesn't look alright, it should be "vscode://", as mentioned in the readme.

**Comment by kgfly** [comment]
"vscod;5C;5^C//" is a typo. Sorry about that.

I figured out. On Linux, "xdg-open" should be used instead of "open", since "open" on Linux is a different thing. 

BTW, a dialog "allow an extension to open this URL?" is always prompted (seems by OS). Do you know if it's possible to disable the annoying dialog?

**Comment by fabiospampinato** [comment]
> BTW, a dialog "allow an extension to open this URL?" is always prompted (seems by OS). Do you know if it's possible to disable the annoying dialog?

It can't be removed by this extension unfortunately. But you should read [this thread](https://github.com/microsoft/vscode/issues/10979), somebody posted an alternative solution that might work better for you.
