### ISSUE TITLE
Feature request: make the plugin searchable in market place.

### ISSUE THREAD

**Issue by kgfly** [fabiospampinato/vscode-debug-launcher#6]
Currently, to install the plugin, I've to run the cmd:
"code --install-extension fabiospampinato.vscode-debug-launcher"
or in vscode, run
"ext install fabiospampinato.vscode-debug-launcher"

It is not possible to memorize this string "fabiospampinato.vscode-debug-launcher", since the string is long and complicated. To install, i've to always open the web and grab in the cmd, which is very inconvenient.

On the other hand, in vscode->menu->view->extensions,

I search 
fabiospampinato
vscode-debug-launcher
fabiospampinato.vscode-debug-launcher

All returned none.

May you please make the plugin searchable in market place? with a reasonable easy memorized name? 

This will make the plugin much more popular!

Thanks.

**Comment by fabiospampinato** [comment]
This is an issue with the marketplace itself, sadly. 

https://github.com/Microsoft/vscode/issues/42890
