### ISSUE TITLE
Update the doc little bit maybe?

### ISSUE THREAD

**Issue by kgfly** [fabiospampinato/vscode-debug-launcher#8]
The doc says:

open 'vscode://fabiospampinato.vscode-debug-launcher/auto?args=/path/to/project' # Trigger `Debug Launcher: Auto` on the provided path
open 'vscode://fabiospampinato.vscode-debug-launcher/file?args=/path/to/foo.js' # Trigger `Debug Launcher: File` on the provided path
open 'vscode://fabiospampinato.vscode-debug-launcher/launch?args={"type":"node","name":"Foo","request":"launch","program":"/path/to/foo.js"}' # Launch the debugger using a custom launch configuration

This only works on Mac actually.

On Linux, it should be
xdg-open 'vscode://fabiospampinato.vscode-debug-launcher/auto?args=/path/to/project' # Trigger `Debug Launcher: Auto` on the provided path
xdg-open 'vscode://fabiospampinato.vscode-debug-launcher/file?args=/path/to/foo.js' # Trigger `Debug Launcher: File` on the provided path
xdg-open 'vscode://fabiospampinato.vscode-debug-launcher/launch?args={"type":"node","name":"Foo","request":"launch","program":"/path/to/foo.js"}' # Launch the debugger using a custom launch configuration

On Windows, it should be
start 'vscode://fabiospampinato.vscode-debug-launcher/auto?args=/path/to/project' # Trigger `Debug Launcher: Auto` on the provided path
start 'vscode://fabiospampinato.vscode-debug-launcher/file?args=/path/to/foo.js' # Trigger `Debug Launcher: File` on the provided path
start 'vscode://fabiospampinato.vscode-debug-launcher/launch?args={"type":"node","name":"Foo","request":"launch","program":"/path/to/foo.js"}' # Launch the debugger using a custom launch configuration

To help the beginner, may you pls update the doc little bit?

**Comment by fabiospampinato** [comment]
Done, thanks 👍

**Comment by kgfly** [comment]
NP :)  

This note is important for linux/windows guys. I would suggest use normal color font instead of gray color font (move it to above paragraph maybe ???). Gray font can be easily ignored. 

Anyway, Thanks for the update. It's your call.
